export const TrendingCard = [
  {
    id: 1,
    imageUrl: "/images/Mask Group.svg",
    title: "Friendy mobile",
    Categories: "Gaming",
    Rate: "120 USD",
  },
  {
    id: 2,
    imageUrl: "/images/Mask Group (3).svg",
    title: "call of Duty",
    Categories: "Gaming",
    Rate: "120 USD",
  },
  {
    id: 3,
    imageUrl: "/images/Mask Group (1).svg",
    title: "Yalla Ludo",
    Categories: "Google play",
    Rate: "120 USD",
  },
  {
    id: 4,
    imageUrl: "/images/Mask Group (2).svg",
    title: "STC quicknet",
    Categories: "Mobile & Data",
    Rate: "120 USD",
  },
  {
    id: 5,
    imageUrl: "/images/Mask Group (5).svg",
    title: "Razer gold",
    Categories: "Gaming",
    Rate: "120 USD",
  },
  {
    id: 6,
    imageUrl: "/images/Mask Group (6).svg",
    title: "Ludo club",
    Categories: "Google play",
    Rate: "120 USD",
  },
  {
    id: 7,
    imageUrl: "/images/Mask Group (7).svg",
    title: "Redbull",
    Categories: "Shopping",
    Rate: "120 USD",
  },
  {
    imageUrl: "/images/Mask Group (8).svg",
    id: 8,
    title: "iTunes",
    Categories: "Subscriptions",
    Rate: "120 USD",
  },
  {
    id: 9,
    imageUrl: "/images/Mask Group (3).svg",
    title: "iTunes",
    Categories: "Subscriptions",
    Rate: "120 USD",
  },
  {
    id: 10,
    imageUrl: "/images/Mask Group (2).svg",
    title: "STC quicknet",
    Categories: "Mobile & Data",
    Rate: "120 USD",
  },
  {
    id: 11,
    imageUrl: "/images/Mask Group (8).svg",
    title: "call of Duty",
    Categories: "Gaming",
    Rate: "120 USD",
  },
  {
    id: 12,
    imageUrl: "/images/Mask Group (6).svg",
    title: "Ludo club",
    Categories: "Google play",
    Rate: "120 USD",
  },
];
